---
- name: Configure Compute Engine instance
  hosts: demo
  become: yes  # Run as root

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install pip (Python package manager)
      apt:
        name: python3-pip
        state: present

    - name: Install virtualenv using pip
      pip:
        name: virtualenv
        executable: pip3
        break_system_packages: true

    - name: Verify installations
      command: "{{ item }}"
      loop:
        - "git --version"
        - "python3 --version"
        - "pip3 --version"
        - "virtualenv --version"
      register: command_output
      changed_when: false

    - name: Show installation results
      debug:
        msg: "{{ command_output.results | map(attribute='stdout') | list }}"

    - name: Clone a public Git repository
      git:
        repo: 'https://github.com/inno-asiimwe/guest-lecture-25.git'
        dest: '/var/demo'
        clone: yes
        update: yes
